server:
  port: 8083

spring:
  application:
    name: project_service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/project_service
    username: postgres
    password: superuser
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

